apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: xixovski-data-science-central-repository
  title: Xixovski data science projects
  description: Central repository of data science projects. 
  annotations:
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  owner: user:guest
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: models
spec:
  targets:
  - ./models/**/**/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: systems
spec:
  targets:
  - ./models/**/catalog-info.yaml

