apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data_science_mono_repo
  description: Repository of data science projects
spec:
  type: service
  owner: user:guest
  lifecycle: production
