apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xixovski data science repository
  description: Repository of data science projects
spec:
  type: service
  owner: user:guest
  lifecycle: production
