apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: data_science_mono_repo
  description: Repository of data science projects
spec:
  type: service
  owner: user:guest
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: models
  description: Individual models
spec:
  targets:
  - ./models/**/catalog-info.yaml
