apiVersion: backstage.io/v1alpha1
kind: System

metadata:
  name: pricing-data-science
  description: Pricing Data Science projects
spec:
  domain: xixovski-data-science-central-repository
  owner: user:guest
  lifecycle: production
