name: Deploy TechDocs

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/docs-builder.yaml
      - catalog-info.yaml
      - mkdocs.yaml
      - docs/**
      - models/**/catalog-info.yaml
      - models/**/mkdocs.yaml
      - models/**/docs/**
      - models/**/**/catalog-info.yaml
      - models/**/**/mkdocs.yaml
      - models/**/**/docs/**


jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Add Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Add Node
        uses: actions/setup-node@v3
      - name: download, validate, install plantuml and its dependencies
        run: sudo apt-get install -y graphviz
      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli
      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==1.*
      - name: Get files changed
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Generate and publish docs
        run: |
          for file in ${{ steps.files.outputs.all }}; do
            if [[ ${file} =~ 'models\/(.+)\/(.+)\/((.+)|(.+)\/(.+))' ]]; then
              cat $(echo ${file} | sed -E 's|^models/([^/]+)/([^/]+)/([^/]+)$|models/\1/\2/catalog-info.yaml|');
            fi 
          done
        #run: techdocs-cli generate --no-docker --verbose
      
